### ISSUE TITLE
Conflicts with Gyroscope-Parallax?

### ISSUE THREAD

**Issue by Ten1o** [IvanMurzak/Unity-Mouse-Parallax#1]
Hi!

I have installed both gyroscope-parallax and mouse-parallax in the same project, and it seems that there are conflicts between these two projects.

![image](https://user-images.githubusercontent.com/33676526/224643527-9c7b3f15-ecc9-45dd-b7cf-82fa47286ed6.png)

**Comment by Ten1o** [comment]
I used openupm to install both packages. The unity version is 2022.1.13f1c1.

**Comment by IvanMurzak** [comment]
@Ten1o thanks for the report. Fixed in this update: https://github.com/IvanMurzak/Unity-Mouse-Parallax/releases/tag/1.0.4
